name: 🚀 Feature Request
description: Suggest a new Instagram tool or feature for the MCP server
title: "[Feature]: "
labels: [enhancement, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide the following details to help us understand your request.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: A concise title for the feature request
      placeholder: e.g., Add tool to get user profile information
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature in detail. What Instagram functionality should this tool provide?
      placeholder: A clear and concise description of what the feature is and how it would work...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain the use case or problem this feature would address
      placeholder: Describe when and why you would use this feature...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Instagram Tool (e.g., get_user_profile, like_post, etc.)
        - Enhancement to Existing Tool
        - MCP Server Improvement (authentication, session management, etc.)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working. Include tool name, parameters, and expected behavior.
      placeholder: |
        Tool name: instagram_<action>
        Parameters:
        - param1: description
        - param2: description
        Expected behavior: ...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to implement this feature myself
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references (e.g., Instagram API documentation, similar tools in other MCP servers)

